import { BillingRecord } from "@/types/admin/societyManagement/billing/Billing";

export const STATIC_DATA: BillingRecord[] = [
  {
    invoiceId: "INV-0001", packageName: "Pro", planType: "Monthly",
    subscriptionStatus: "Active", paymentStatus: "Paid", amount: 999,
    currency: "INR", currencySymbol: "₹", paymentMethod: "UPI",
    startDate: "01 Jan 2025", endDate: "31 Jan 2025", nextBillingDate: "01 Feb 2025",
    createdAt: "01 Jan 2025", customerName: "Rajesh Kumar",
    customerPhone: "+91 98765 43210", tax: 180, discount: 0,
    societyName: "Greenwood Heights",
    societyAddress: "Plot 12, Sector 4\nBhubaneswar, Odisha – 751024",
  },
  {
    invoiceId: "INV-0002", packageName: "Basic", planType: "Annual",
    subscriptionStatus: "Active", paymentStatus: "Paid", amount: 4999,
    currency: "INR", currencySymbol: "₹", paymentMethod: "Card",
    startDate: "15 Jan 2025", endDate: "14 Jan 2026", nextBillingDate: "15 Jan 2026",
    createdAt: "15 Jan 2025", customerName: "Priya Sharma",
    customerPhone: "+91 91234 56789", tax: 900, discount: 500,
    societyName: "Sunrise Apartments",
    societyAddress: "Block B, Patia\nBhubaneswar, Odisha – 751031",
  },
  {
    invoiceId: "INV-0003", packageName: "Premium", planType: "Monthly",
    subscriptionStatus: "Inactive", paymentStatus: "Failed", amount: 1999,
    currency: "INR", currencySymbol: "₹", paymentMethod: "Net Banking",
    startDate: "01 Dec 2024", endDate: "31 Dec 2024", nextBillingDate: "—",
    createdAt: "01 Dec 2024", customerName: "Arjun Mehta",
    customerPhone: "+91 99887 76655", tax: 360, discount: 0,
    societyName: "Silver Oaks Residency",
    societyAddress: "NH-16 Bypass, Rasulgarh\nBhubaneswar, Odisha – 751010",
  },
  {
    invoiceId: "INV-0004", packageName: "Standard", planType: "One-time",
    subscriptionStatus: "Expired", paymentStatus: "Paid", amount: 2499,
    currency: "INR", currencySymbol: "₹", paymentMethod: "Wallet",
    startDate: "10 Nov 2024", endDate: "10 Feb 2025", nextBillingDate: "—",
    createdAt: "10 Nov 2024", customerName: "Sneha Patel",
    customerPhone: "+91 90000 11223", tax: 450, discount: 200,
    societyName: "Palm Grove Enclave",
    societyAddress: "Sailashree Vihar\nBhubaneswar, Odisha – 751021",
  },
  {
    invoiceId: "INV-0005", packageName: "Basic", planType: "Monthly",
    subscriptionStatus: "Cancelled", paymentStatus: "Refunded", amount: 999,
    currency: "INR", currencySymbol: "₹", paymentMethod: "UPI",
    startDate: "01 Mar 2025", endDate: "31 Mar 2025", nextBillingDate: "—",
    createdAt: "01 Mar 2025", customerName: "Vikram Singh",
    customerPhone: "+91 88123 45670", tax: 180, discount: 0,
    societyName: "The Monarch Residences",
    societyAddress: "IRC Village, Nayapalli\nBhubaneswar, Odisha – 751015",
  },
  {
    invoiceId: "INV-0006", packageName: "Pro", planType: "Annual",
    subscriptionStatus: "Active", paymentStatus: "Pending", amount: 7999,
    currency: "INR", currencySymbol: "₹", paymentMethod: "Card",
    startDate: "20 Feb 2025", endDate: "19 Feb 2026", nextBillingDate: "20 Feb 2026",
    createdAt: "20 Feb 2025", customerName: "Ananya Iyer",
    customerPhone: "+91 77456 78901", tax: 1440, discount: 1000,
    societyName: "Lakeview Township",
    societyAddress: "Chandrasekharpur\nBhubaneswar, Odisha – 751023",
  },
  {
    invoiceId: "INV-0007", packageName: "Premium", planType: "Monthly",
    subscriptionStatus: "Active", paymentStatus: "Paid", amount: 3499,
    currency: "INR", currencySymbol: "₹", paymentMethod: "UPI",
    startDate: "05 Mar 2025", endDate: "04 Apr 2025", nextBillingDate: "05 Apr 2025",
    createdAt: "05 Mar 2025", customerName: "Rohit Verma",
    customerPhone: "+91 93456 12345", tax: 630, discount: 0,
    societyName: "Horizon Valley Homes",
    societyAddress: "Niladri Vihar, Khandagiri\nBhubaneswar, Odisha – 751030",
  },
  {
    invoiceId: "INV-0008", packageName: "Standard", planType: "Annual",
    subscriptionStatus: "Inactive", paymentStatus: "Failed", amount: 9999,
    currency: "INR", currencySymbol: "₹", paymentMethod: "Net Banking",
    startDate: "01 Jan 2024", endDate: "31 Dec 2024", nextBillingDate: "—",
    createdAt: "01 Jan 2024", customerName: "Kavya Nair",
    customerPhone: "+91 84321 09876", tax: 1800, discount: 500,
    societyName: "Emerald Gardens",
    societyAddress: "Aerodrome Area, Pokhariput\nBhubaneswar, Odisha – 751020",
  },
]